apiVersion: 1

datasources:
  - name: Usage Tracker Postgres
    uid: usage-tracker-pg
    type: postgres
    access: proxy
    url: database:5432
    database: usage_tracker
    user: usage_tracker
    isDefault: true
    editable: false
    jsonData:
      sslmode: disable
      postgresVersion: 1500
    secureJsonData:
      password: $DB_PASSWORD
